ALTER TABLE mst_language 
  ADD COLUMN IF NOT EXISTS is_display_client BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS create_at TIMESTAMP default NOW(),
  ADD COLUMN IF NOT EXISTS update_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS create_by UUID,
  ADD COLUMN IF NOT EXISTS update_by UUID